database: 
  path: "data/invoice_warehouse.duckdb"

schemas:
  raw: "raw"
  dev: "dev"
  blue: "prod_blue"
  green: "prod_green"

tables:
  customers: "customers"
  invoices: "invoices"
  invoice_line_items: "invoice_line_items"

raw_data:
  raw_data_path: "data/raw_sample_data/"
